version: '3.4'

services:
  gatewayservice:
    container_name: gatewayservice
    image: ${DOCKER_REGISTRY-}gatewayservice
    ports:
      - "5147:80"
    depends_on: 
      - pokemon_db
    build:
      context: .
      dockerfile: GatewayService\Dockerfile
    networks:
      - common_network
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=pokemon_db;Port=5432;Database=PokemonDb; IntegratedSecurity=true;Pooling=true
      - ASPNETCORE_URLS=http://+:80
    expose:
      - "80"

  pokemonservice:
    container_name: pokemonservice
    image: ${DOCKER_REGISTRY-}pokemonservice
    ports:
      - "5228:80"
    depends_on: 
      - pokemon_db
      - pokemon_pubsub
      - databaseupdaterservice
    build:
      context: .
      dockerfile: PokemonService\Dockerfile
    networks:
      - common_network
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=pokemon_db;Port=5432;Database=PokemonDb; IntegratedSecurity=true;Pooling=true
      - ASPNETCORE_URLS=http://+:80
    expose:
      - "80"

  translationservice:
    container_name: translationservice
    image: ${DOCKER_REGISTRY-}translationservice
    ports:
      - "5128:80"
    depends_on: 
      - pokemon_db
    build:
      context: .
      dockerfile: TranslationService\Dockerfile
    networks:
      - common_network
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=pokemon_db;Port=5432;Database=PokemonDb; IntegratedSecurity=true;Pooling=true
      - ASPNETCORE_URLS=http://+:80
    expose:
      - "80"

  databaseupdaterservice:
    container_name: dbupdaterservice
    image: ${DOCKER_REGISTRY-}databaseupdaterservice
    ports:
      - "5256:80"
    depends_on: 
      - pokemon_db
      - pokemon_pubsub
    build:
      context: .
      dockerfile: DatabaseUpdaterService/Dockerfile
    networks:
      - common_network
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=pokemon_db;Port=5432;Database=PokemonDb; IntegratedSecurity=true;Pooling=true
      - ASPNETCORE_URLS=http://+:80
    expose:
      - "80"

  pokemon_db:
    image: postgres:latest
    container_name: pokemon_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=PokemonDb
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - common_network

  pokemon_pubsub:
    image: 3apag/pubsub-emulator
    environment:
      - PUBSUB_PROJECT_ID=project-test
      - PUBSUB_LISTEN_ADDRESS=0.0.0.0:8432
    ports:
      - 8432:8432
    volumes:
      - pubsub_data:/opt/data
    restart: always
    container_name: pokemon_pubsub
    networks:
      - common_network

volumes:
  app_data:
  pubsub_data:

networks:
  common_network:



